import 'package:flutter/material.dart';

Map<int, Color> color = {
  50: Color.fromRGBO(43, 28, 72, .1),
  100: Color.fromRGBO(43, 28, 72, .2),
  200: Color.fromRGBO(43, 28, 72, .3),
  300: Color.fromRGBO(43, 28, 72, .4),
  400: Color.fromRGBO(43, 28, 72, .5),
  500: Color.fromRGBO(43, 28, 72, .6),
  600: Color.fromRGBO(43, 28, 72, .7),
  700: Color.fromRGBO(43, 28, 72, .8),
  800: Color.fromRGBO(43, 28, 72, .9),
  900: Color.fromRGBO(43, 28, 72, 1),
};

List<String> states = ["Delhi", "Haryana", "Odisha"];

Map<int, String> vaccineIndices = {0: "COVISHIELD", 1: "ANY", 2: "COVAXIN"};
Map<int, String> vaccineDoseIndices = {0: "Dose-1", 1: "ANY", 2: "Dose-2"};

Map<String, List<String>> districtsInState = {
  "Haryana": [
    "Ambala",
    "Bhiwani",
    "Charkhi Dadri",
    "Faridabad",
    "Fatehabad",
    "Gurgaon",
    "Hisar",
    "Jhajjar",
    "Jind",
    "Kaithal",
    "Karnal",
    "Kurukshetra",
    "Mahendragarh",
    "Nuh",
    "Palwal",
    "Panchkula",
    "Panipat",
    "Rewari",
    "Rohtak",
    "Sirsa",
    "Sonipat",
    "Yamunanagar"
  ],
  "Odisha": [
    "Angul",
    "Balangir",
    "Balasore",
    "Bargarh",
    "Bhadrak",
    "Boudh",
    "Cuttack",
    "Deogarh",
    "Dhenkanal",
    "Gajapati",
    "Ganjam",
    "Jagatsinghpur",
    "Jajpur",
    "Jharsuguda",
    "Kalahandi",
    "Kandhamal",
    "Kendrapara",
    "Kendujhar",
    "Khurda",
    "Koraput",
    "Malkangiri",
    "Mayurbhanj",
    "Nabarangpur",
    "Nayagarh",
    "Nuapada",
    "Puri",
    "Rayagada",
    "Sambalpur",
    "Subarnapur",
    "Sundargarh",
  ],
  "Delhi": [
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "North East Delhi",
    "North West Delhi",
    "Shahdara",
    "South Delhi",
    "South East Delhi",
    "South West Delhi",
    "West Delhi"
  ],
};

Map<String, int> districtCodes = {
  "Ambala": 193,
  "Angul": 445,
  "Balangir": 448,
  "Balasore": 447,
  "Bargarh": 472,
  "Bhadrak": 454,
  "Bhiwani": 200,
  "Boudh": 468,
  "Central Delhi": 141,
  "Charkhi Dadri": 201,
  "Cuttack": 457,
  "Deogarh": 473,
  "Dhenkanal": 458,
  "East Delhi": 145,
  "Faridabad": 199,
  "Fatehabad": 196,
  "Gajapati": 467,
  "Ganjam": 449,
  "Gurgaon": 188,
  "Hisar": 191,
  "Jagatsinghpur": 459,
  "Jajpur": 460,
  "Jhajjar": 189,
  "Jharsuguda": 474,
  "Jind": 204,
  "Kaithal": 190,
  "Kalahandi": 464,
  "Kandhamal": 450,
  "Karnal": 203,
  "Kendrapara": 461,
  "Kendujhar": 455,
  "Khurda": 446,
  "Koraput": 451,
  "Kurukshetra": 186,
  "Mahendragarh": 206,
  "Malkangiri": 469,
  "Mayurbhanj": 456,
  "Nabarangpur": 470,
  "Nayagarh": 462,
  "New Delhi": 140,
  "North Delhi": 146,
  "North East Delhi": 147,
  "North West Delhi": 143,
  "Nuapada": 465,
  "Nuh": 205,
  "Palwal": 207,
  "Panchkula": 187,
  "Panipat": 195,
  "Puri": 463,
  "Rayagada": 471,
  "Rewari": 202,
  "Rohtak": 192,
  "Sambalpur": 452,
  "Shahdara": 148,
  "Sirsa": 194,
  "Sonipat": 198,
  "South Delhi": 149,
  "South East Delhi": 144,
  "South West Delhi": 150,
  "Subarnapur": 466,
  "Sundargarh": 453,
  "West Delhi": 142,
  "Yamunanagar": 197
};
